scraper:
  timeout: 1 # Seconds before fetching next week's schedule
  course_name: "Mestrado em Computação Avançada"
  year: 1
  week:
    start: "2025-09-15"
    end: "2026-01-30"

export:
  json:
    file_name: "out.json"
    indent: True

  #ics:
  #  file_name: "out.ics"