scraper:
  timeout: 1 # Seconds before fetching next week's schedule
  course_name: "Mestrado em Computação Avançada"
  year: 1
  week:
    start: "2025-09-15"
    end: "2025-10-01"
  #classes:
    #- "Sistemas e Arquiteturas de Computadores"
    #- "Ferramentas de Computação de Elevado Desempenho"

export:
  json:
    file_name: "out.json"
    indent: True

  #ics:
  #  file_name: "./export/out.ics"
  #  override_file: "./export/out.ics"